version: '3.4'

services:
  flask-server:
    image: flask_debug_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 10001:10001
    volumes:
      - .:/app:cached
